### PR TITLE
Add option to ignore hidden files

### PR DESCRIPTION
**Pull request by djflorio**
I'm using your module to log the files on all of my external hard drives, and it works great! The only issue is that I don't want to log hidden files, and some of my drives have TONS of them. I figured it would be nice to have the option to hide those.

Not sure if you're accepting contributions, but here are my changes if so.

### CODE REVIEW

**Comment by manidlou** [comment]
@djflorio thanks for your contribution. Any contributions definitely welcome here!

That's a good idea to add the `hidden` option. The only thing is I think that'd be better if we used one optional `opts` object with `{label, hidden}` properties instead of having two optional arguments (It would make sense to have it like that if we had only one optional argument).

So, will you please apply that to your PR?

**Comment by djflorio** [comment]
@manidlou that makes sense. I've combined the optional arguments into an object and updated the tests/README.

**Comment by manidlou** [comment]
@djflorio code LGTM! Will you squash this please?

**Comment by djflorio** [comment]
@manidlou sure thing, how's this? Still a bit new to collaborating on Github, so thanks for your patience!

**Comment by manidlou** [comment]
@djflorio no worries! We all start from somewhere. no need to rush this! I suggest you to read https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request. It helps you understand the git rebase. Particularly, the part about [squash your changes](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes) is very helpful and shows you how to squash your commits into one commit. Let me know if you encounter with any questions. I'm more than happy to help you any way that I can.

**Comment by djflorio** [comment]
@manidlou thanks for the documentation! I'll definitely give it a good read. Is there an issue with the PR as of now? I believe I have it squashed to a single commit. Thanks!

**Comment by manidlou** [comment]
LGTM!

**Comment by manidlou** [comment]
@djflorio thanks for your contribution! Will be published shortly.

**Comment by djflorio** [comment]
@manidlou no problem! Glad to contribute and thanks for the tips.

**Comment by manidlou** [comment]
@djflorio I just published `v4.0.0`!

**Pull request merged**
